version: "2"

services:
  nginx:
    image: nginx
    command: /files/start.sh
    ports:
      - "80:80"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - ./files:/files

#  crowd:
#    image: blacklabelops/crowd
#    volumes:
#      - crowd-data:/var/atlassian/crowd
#    environment:
#      CROWD_URL: http://localhost:8095/crowd
#      CROWD_PROXY_NAME: crowd.${REVERSE_PROXY_DOMAIN_NAME}
#      CROWD_PROXY_PORT: 443
#      CROWD_PROXY_SCHEME: https
#      CROWD_PROXY_SECURE: "true"
#      LOGIN_BASE_URL: https://crowd.${REVERSE_PROXY_DOMAIN_NAME}
#      CROWD_CONTEXT: crowd

  jira:
    image: cptactionhank/atlassian-jira-software
    environment:
      X_PROXY_NAME: jira.${DOMAIN_NAME}
      X_PROXY_PORT: 80
      X_PROXY_SCHEME: http
    volumes:
      - jira-data:/var/atlassian/jira
      - jira-logs:/opt/atlassian/jira/logs

  gogs:
    image: gogs/gogs
    volumes:
      - gogs-data:/data

  jenkins:
    image: jenkins/jenkins:lts
    hostname: jenkins
    volumes:
      - jenkins-home:/var/jenkins_home

volumes:
  jira-data:
    driver: local
  jira-logs:
    driver: local
  gogs-data:
    driver: local
  jenkins-home:
    driver: local
