version: "2"

services:
  nginx:
    image: nginx
    command: /files/start.sh
    ports:
      - "80:80"
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./files:/files

  jira:
    image: cptactionhank/atlassian-jira-software
    environment:
      X_PROXY_NAME: jira.${DOMAIN}
      X_PROXY_PORT: 80
      X_PROXY_SCHEME: http
    volumes:
      - jira-data:/var/atlassian/jira
      - jira-logs:/opt/atlassian/jira/logs

  gogs:
    image: gogs/gogs
    volumes:
      - gogs-data:/data

  jenkins:
    image: jenkins/jenkins:lts
    hostname: jenkins
    volumes:
      - jenkins-home:/var/jenkins_home

volumes:
  jira-data:
    driver: local
  jira-logs:
    driver: local
  gogs-data:
    driver: local
  jenkins-home:
    driver: local
